services:
  - type: web
    name: menuwise-backend-api
    env: node
    buildCommand: npm ci && npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: menuwise-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: REPLIT_DOMAINS
        sync: false
      - key: REPL_ID
        sync: false
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: PIXABAY_API_KEY
        sync: false

databases:
  - name: menuwise-db
    databaseName: menuwise
    user: menuwise_user
